# Generated by Django 4.1.7 on 2024-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('delta_tp9', models.FloatField()),
                ('delta_af7', models.FloatField()),
            ],
        ),
    ]
